### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by eggplants** [shihono/alphabet2kana#3]
```toml
[tool.poetry.scripts]
a2k = 'alphabet2kana.main:main'
```

```bash
a2k -h
a2k -v
a2k "text"
a2k "text" [-d, --delimiter=None] [-n, --numeral=False]
```
